### ISSUE TITLE
`--mz-url` cannot correctly parse postgres options

### ISSUE THREAD

**Issue by jamii** [MaterializeInc/chbenchmark#9]
If I start with `chbenchmark --mz-url='postgresql://localhost:6875/?sslmode=disable'` I get 

```
terminate called after throwing an instance of 'pqxx::broken_connection'
  what():  invalid connection option "postgresql://localhost:6875/?sslmode"
```

It seems that the `=` gets eaten by opt parsing

**Comment by umanwizard** [comment]
I will look into this on Monday

**Comment by umanwizard** [comment]
Spoke with Jamie, apparently this can no longer be reproed.
